language: scala

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use $_ && java -Xmx32m -version

env:
  matrix:
    - TRAVIS_JDK=adopt@1.8.202-08

script:
  # Code validations
  - scripts/validate-code-style
  - sbt +test
  - sbt +publishLocal
  - sbt plugin/scripted
  # Generate documentation
  - sbt docs/webStage

cache:
  directories:
  - $HOME/.jabba/jdk
  - $HOME/.ivy2/cache
  - $HOME/.sbt/
