language: scala

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use $_ && java -Xmx32m -version

env:
  - SCRIPT="sbt +test"              TRAVIS_JDK=adopt@1.8.202-08
  - SCRIPT="sbt +publishLocal"      TRAVIS_JDK=adopt@1.8.202-08
  - SCRIPT="sbt plugin/scripted"    TRAVIS_JDK=adopt@1.8.202-08
  - SCRIPT="sbt docs/generateDocs"  TRAVIS_JDK=adopt@1.8.202-08

script:
  - $SCRIPT

cache:
  directories:
  - $HOME/.jabba/jdk
  - $HOME/.ivy2/cache
  - $HOME/.sbt/
